### ISSUE TITLE
GSspell doesn't compile

### ISSUE THREAD

**Issue by Strahinja** [gnustep/libs-gui#214]
I'm trying to get GNUstep working on Alpine Linux v3.18, but `libs-gui` fails to compile. The errors I'm getting are a bunch of:
```
/usr/bin/ld: ../Source/./obj/libgnustep-gui.so: undefined reference to `__objc_class_name_NSUndoManager'
/usr/bin/ld: ../Source/./obj/libgnustep-gui.so: undefined reference to `__objc_class_name_NSTextView'
/usr/bin/ld: ../Source/./obj/libgnustep-gui.so: undefined reference to `__objc_class_name_NSColorList'
```
and so on (full log when retrying `make messsages=yes` is [attached](https://github.com/gnustep/libs-gui/files/13506146/make.log)).

Clang reports the following:
```
$ clang --version
Alpine clang version 16.0.6
Target: x86_64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
```

`libobjc*` on my system:
```
$ find /usr -name 'libobjc*' 2>/dev/null
/usr/local/lib/pkgconfig/libobjc.pc
/usr/local/lib/libobjc.so.4.6
/usr/local/lib/libobjc.so
```

The commands I used to configure various parts up to that point were:

```
#!/bin/sh
# mk-tools-make.sh
./configure --with-library-combo=ng --with-runtime-abi=gnustep-2.0 && make
```

```
#!/bin/sh
# mk-libobjc2.sh
OBJC=clang
CC=clang
CPP="clang -E"
OBJCXX=clang++
CXX=clang++

export OBJC CC CPP OBJCXX CXX

if [ -e Build ]; then
	rm -fr Build
fi
mkdir Build
cd Build
cmake .. && make
```

```
#!/bin/sh
# mk-libs-base.sh
OBJC=clang
CC=clang
CPP="clang -E"
OBJCXX=clang++
CXX=clang++
ICONV=gnu-iconv
LIBS="-lobjc"

export OBJC CC CPP OBJCXX CXX ICONV
export OBJCFLAGS OBJCXXFLAGS LIBS

./configure && make
```

```
#!/bin/sh
# mk-libs-gui.sh

OBJC=clang
CC=clang
CPP="clang -E"
OBJCXX=clang++
CXX=clang++
ICONV=gnu-iconv

export OBJC CC CPP OBJCXX CXX ICONV

./configure && make
```

I would appreciate any information on what am I possibly doing wrong here.

**Comment by Strahinja** [comment]
I tried compiling a small test program:
```objc
// main.m
#import <Foundation/Foundation.h>

int
main(int argc, const char** argv)
{
	@autoreleasepool
	{
		NSLog(@"Hello, world!");
	}
	return 0;
}
```
which only worked (with warnings) when compiled as:
```
$ clang -x objective-c -fblocks -fobjc-runtime=gnustep-2.0 -o hello main.m -L/usr/local/lib -lgnustep-base -lobjc
In file included from main.m:2:
In file included from /usr/local/include/Foundation/Foundation.h:200:
In file included from /usr/include/dispatch/dispatch.h:32:
In file included from /usr/include/os/generic_unix_base.h:27:
/usr/include/sys/cdefs.h:4:2: warning: usage of non-standard #include <sys/cdefs.h> is deprecated [-W#warnings]
    4 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^
In file included from main.m:2:
In file included from /usr/local/include/Foundation/Foundation.h:200:
In file included from /usr/include/dispatch/dispatch.h:70:
In file included from /usr/include/dispatch/source.h:35:
/usr/include/sys/signal.h:1:2: warning: redirecting incorrect #include <sys/signal.h> to <signal.h> [-W#warnings]
    1 | #warning redirecting incorrect #include <sys/signal.h> to <signal.h>
      |  ^
2 warnings generated.
```
However, adding
```sh
OBJCFLAGS="-fblocks -fobjc-runtime=gnustep-2.0"
OBJCXXFLAGS="$OBJCFLAGS"
export OBJCFLAGS OBJCXXFLAGS
```
to both the build of `libs-base` and `libs-gui` changed nothing, I'm getting the same errors about undefined symbols. Running `make messages=yes` reveals the following command line is used to compile the offending source file:
```
clang      -pthread -fexceptions -rdynamic -fobjc-runtime=gnustep-2.0 \
   -fblocks  -o GSspell.service/./GSspell ./obj/GSspell.obj/GSspell.m.o \
   -L../Source/./obj -L../Model/./obj -L/home/strajder/GNUstep/Library/Libraries \
   -L/usr/local/lib -L/usr/lib  -licui18n -licuuc -licudata  -L/usr/lib -lpng16 \
   -lgnustep-gui -laspell -lpng -ltiff -lz -ljpeg -lm -lobjc \
   -lgnustep-base   -lpthread -lobjc   -lm
```

**Comment by fredkiefer** [comment]
You seem to have quite a few issues here, Maybe it would be best to start step by step and ensure that each level is fully working before adding another on top.

There a some obvious things wrong. For example you did not recompile GNUstep make after setting up your runtime. As you seem to compile libobjc2 with out the help of GNUstep make, it would be best just to swap these two. Next you never sourced the GNUstep environment file after building make. You also just built the different components but never installed them ("make install"). As far as I remember that should not stop them from building but needs to be done for a real production environment.

The wrong header files in your second post seem to either come from libdispatch or are an issue with system include files themselves. Nothing we can do about that.

I would suggest you start by changing the compilation order and then after building base run the tests there to see whether base is actually functional.

**Comment by Strahinja** [comment]
The scripts I quoted are just meant for building, not installing the components. After every component is built, I ran `doas make install` manually. Also I sourced _GNUstep.sh_ manually in the shell after installing `tools-make`:
```
. /usr/local/share/GNUstep/Makefiles/GNUstep.sh
```

> For example you did not recompile GNUstep make after setting up your runtime.

Is this needed? So, if I understand correctly, it is necessary to compile and install `tools-make` once without `libobjc2` installed, then compile and install `libobjc2`, and then recompile and install `tools-make` again? If so, are there any special switches needed, or a different command other than `make`, then `make install` as root to "use GNUstep make"?

I tried running `make check` with `libs-base`, but a lot of the tests failed. I didn't thought that relevant, since from the time I compiled LFS, I know that for things like GCC, failing a lot of tests is normal, especially at specific points in LFS build.

Running `make check` gives:
```
   8278 Passed tests
   1354 Failed tests
     36 Dashed hopes
      5 Skipped sets
      1 Failed set
      1 Failed file
```
Full [tests.log here](https://github.com/gnustep/libs-gui/files/13517822/tests.log).

**Comment by Strahinja** [comment]
I have managed to make the TLS checks succeed by setting the absolute path to certtool in _Source/GSTLS.m_ with this patch:
```
From 39801ecf9fa514cc530b64d45782a401f1d7691d Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?=D0=A1=D1=82=D1=80=D0=B0=D1=85=D0=B8=D1=9A=D0=B0=20=D0=A0?=
 =?UTF-8?q?=D0=B0=D0=B4=D0=B8=D1=9B?= <contact@strahinja.org>
Date: Sun, 3 Dec 2023 10:05:30 +0100
Subject: [PATCH] Source/GSTLS.m: Fix gnutls on Alpine Linux
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Signed-off-by: Страхиња Радић <contact@strahinja.org>
---
 Source/GSTLS.m | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Source/GSTLS.m b/Source/GSTLS.m
index b8a179361..aa425d0cb 100644
--- a/Source/GSTLS.m
+++ b/Source/GSTLS.m
@@ -1151,7 +1151,7 @@ static NSMutableDictionary      *credentialsCache = nil;
       [tmp writeToFile: tmpTmp atomically: NO];
 
       task = [NSTask new];
-      [task setLaunchPath: @"certtool"];
+      [task setLaunchPath: @"/usr/bin/certtool"];
       [task setArguments: [NSArray arrayWithObjects:
 	@"--generate-privkey", @"--sec-param", @"high", @"--outfile", tmpKey,
 	nil]];
@@ -1163,7 +1163,7 @@ static NSMutableDictionary      *credentialsCache = nil;
       key = [NSData dataWithContentsOfFile: tmpKey];
 
       task = [NSTask new];
-      [task setLaunchPath: @"certtool"];
+      [task setLaunchPath: @"/usr/bin/certtool"];
       [task setArguments: [NSArray arrayWithObjects:
 	@"--generate-self-signed", @"--load-privkey", tmpKey,
 	@"--template", tmpTmp, @"--outfile", tmpCrt,
-- 
2.43.0
```
The result:
```
   8276 Passed tests
   1358 Failed tests
     31 Dashed hopes
      1 Skipped set
      1 Failed file
```

**Comment by fredkiefer** [comment]
This can only mean that your system doesn't have `/usr/bin` in its standard path. There may be reasons for this, but they are beyond me.

**Comment by Strahinja** [comment]
https://github.com/gnustep/libs-base/issues/356#issuecomment-1837558776

**Comment by Strahinja** [comment]
Following the advice at [StackOverflow](https://stackoverflow.com/questions/7751640/undefined-reference-to-gxx-personality-sj0/13283268#13283268), I managed to build GSspell and other packages. What I did was issue a simple
```
$ make clean
```
before recompilation.
