### PR TITLE
Add missing #import <AppKit/AppKitDefines.h> to NSSound.h

### PR DESCRIPTION
**Pull request by buzzdeee**
This broke building SimpleAgenda for me:

In file included from SoundBackend.m:1:
/usr/local/include/AppKit/NSSound.h:57:1: error: unknown type name 'APPKIT_EXPORT_CLASS' APPKIT_EXPORT_CLASS

### CODE REVIEW

**Comment by gcasa** [comment]
Could you please share how this breaks Gorm because I haven't seen this.

**Comment by 0-wiz-0** [comment]
Ah sorry. It was a problem with Gorm 1.2.23 but it is working fine in 1.2.28.

**Review by gcasa — APPROVED** [review]
This change looks fine to me.

**Review by fredkiefer — APPROVED** [review]

**Comment by gcasa** [comment]
I'm going to merge this change since it is trivial.
