### ISSUE TITLE
Compile error with FreeBSD 15.1 amd64

### ISSUE THREAD

**Issue by pkgdemon** [gnustep/libs-gui#633]
@fredkiefer @DTW-Thalion 

I believe this commit is responsible for breaking build on FreeBSD 15.1

 https://github.com/gnustep/libs-gui/commit/237f4fdd009b87c433fa1f21606b07c86c14b356

```
 Compiling file NSSlider.m ...
 Compiling file NSSliderCell.m ...
NSPathControl.m:90:7: error: use of undeclared identifier '_editable'
   90 |       _editable = YES;
      |       ^
NSPathControl.m:277:10: error: use of undeclared identifier '_editable'
  277 |   return _editable;
      |          ^
NSPathControl.m:282:3: error: use of undeclared identifier '_editable'
  282 |   _editable = flag;
      |   ^
3 errors generated.
gmake[5]: *** [/System/Library/Makefiles/rules.make:534: obj/libgnustep-gui.obj/NSPathControl.m.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
gmake[4]: *** [/System/Library/Makefiles/Instance/library.make:286: internal-library-all_] Error 2
gmake[3]: *** [/System/Library/Makefiles/Master/rules.make:297: libgnustep-gui.all.library.variables] Error 2
gmake[2]: *** [/System/Library/Makefiles/Master/library.make:37: internal-all] Error 2
gmake[1]: *** [/System/Library/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
gmake[1]: Leaving directory '/Developer/Library/Sources/libs-gui'
*** Error code 1

Stop.
make: stopped making "install" in /Developer
```

**Comment by pkgdemon** [comment]
Sorry for the false alarm.  This was a local issue on my end.  I tried a fresh setup and it works fine.  I suspected a real regression due to the sheer number of commits by the same person.

**Comment by DTW-Thalion** [comment]
Glad it was a anomaly ! Last thing I want is to be offside with BSD. :) Keep an eye out as the next couple of weeks will have a large number of commits between now and August 7th - after that things should calm down considerably.
